language: python

sudo: false   # use container-based infrastructure

python:
    - "3.4"
    - "3.5"

install:
    - travis_wait pip install -r requirements.txt

script:
    - coverage run setup.py test

notifications:
    email: false